[package]
name = "gtfs-parsing"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
protobuf = "3.7.2"
serde = { version = "1.0.219", features = ["derive"] }
zip = {version = "2.6.0", optional = true}

[features]
default = ["zip"]
zip = ["dep:zip"]
